apiVersion: apps/v1
kind: Deployment
metadata:
  name: outyet
spec:
  selector:
    matchLabels:
      run: outyet
  replicas: 3
  template:
    metadata:
      labels:
        run: outyet
    spec:
      containers:
      - name: outyet
        image: 192.168.1.100:5000/lduhejian/outyet:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: outyet-svc
spec:
  type: NodePort
  selector:
    run: outyet
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 8080
